apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-pesbuk
data:
  config.php: |
    <?php
    $db_host = "db-stagging.cp9p94zrg0us.ap-southeast-1.rds.amazonaws.com";
    $db_user = "admin";
    $db_pass = "rafli001";
    $db_name = "dbsosmed";
    try {    
      //create PDO connection
      $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
      //show error
      die("Terjadi masalah: " . $e->getMessage());
    }
    ?>
