# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pesbuk-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: sosmed.rafli24.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pesbuk-service
                port:
                  number: 80
